version: 3.8
services:
  phpinfo:
    deploy:
      mode: replicated
      placement: 
        constraints: 
          - node.role==worker
      replicas: 2
    image: atoz110/simplilearn-phpinfo:latest
    ports:
      - 80:8080
