apiVersion: v1
kind: Pod
metadata:
  name: simplilearn-
spec:
  containers:
  - name: sim
    image: ubuntu:trusty
    command:
      - "php"
    args:
      - "-f"
      - "index.php"
      - "-S"
      - "0.0.0.0:8080"
